updated policy and added string formating

diff --git a/getbib b/getbib
--- a/getbib
+++ b/getbib
@@ -2,8 +2,8 @@
 # File              : getbib
 # Author            : David Barcene <david.barcene@utp.ac.pa>
 # Date              : 01.03.2022
-# Last Modified Date: 24.04.2022
-# Last Modified By  : David Barcene <david.barcene@utp.ac.pa>
+# Last Modified Date: 13.04.2026
+# Last Modified By  : David Barcene <dbarcene@indicasat.org.pa>
 
 # Based on nixcasts youtube video Writing academic papers on the command 
 # line with pandoc, and Luke Smith script getbib, but added the rules of
@@ -11,18 +11,28 @@
 # Change User-Agent info  with your own before using it.
 # Copy this file into your ~/.local/bin/
 
-[ -z "$1" ] && echo "Usage: getbib [pdf] or getbib [doi]" && exit
+[ -z "$1" ] && echo "Usage: getbib [pdf] or getbib [doi]
+Requires pdfinfo if you are parsing a pdf" && exit
 
 if [ -f "$1" ]; then
-	doi=$(pdfinfo "$1" | grep -io "doi:.*") ||
-	doi=$(pdftotext "$1" 2>/dev/null - | grep -io "doi.*" -m 1 | sed "s/^..../doi:/") ||
-	exit 1
+    # Extract the DOI and immediately strip the "doi:" prefix if it exists
+    doi=$(pdfinfo "$1" | grep -ioP "10\.\d{4,9}/[-._;()/:A-Z0-9]+" ||
+          pdftotext "$1" - | grep -ioP "10\.\d{4,9}/[-._;()/:A-Z0-9]+" -m 1)
+
+    [ -z "$doi" ] && echo "Error: Could not find DOI in PDF." && exit 1
 else
-	doi="$1"
+    # If passed manually, strip "doi:" prefix just in case
+    doi="${1#doi:}"
 fi
 
 # Check crossref.org for bibtex citation
-curl -X GET \
+output=$(curl -X GET \
 	"https://api.crossref.org/works/$doi/transform/application/x-bibtex" \
 	-H 'User-Agent: dbarcene (mailto:david.barcene@utp.ac.pa)' \
-	-w "\\n"
+	-w "\\n")
+
+formatted="${output#?}"
+formatted="${formatted//,/,$'\n\t'}"
+formatted="${formatted%\}*}"$'\n}'
+
+echo "$formatted"
