added gitignore, getbib check for poppler-utils

diff --git a/getbib b/getbib
--- a/getbib
+++ b/getbib
@@ -2,7 +2,7 @@
 # File              : getbib
 # Author            : David Barcene <david.barcene@utp.ac.pa>
 # Date              : 01.03.2022
-# Last Modified Date: 13.04.2026
+# Last Modified Date: 15.04.2026
 # Last Modified By  : David Barcene <dbarcene@indicasat.org.pa>
 
 # Based on nixcasts youtube video Writing academic papers on the command 
@@ -15,20 +15,23 @@
 Requires pdfinfo if you are parsing a pdf" && exit
 
 if [ -f "$1" ]; then
-    # Extract the DOI and immediately strip the "doi:" prefix if it exists
-    doi=$(pdfinfo "$1" | grep -ioP "10\.\d{4,9}/[-._;()/:A-Z0-9]+" ||
-          pdftotext "$1" - | grep -ioP "10\.\d{4,9}/[-._;()/:A-Z0-9]+" -m 1)
-
-    [ -z "$doi" ] && echo "Error: Could not find DOI in PDF." && exit 1
+	if ![ -x "pdfinfo" ]; then 
+		echo "Error: pdfinfo not found." && exit 1
+	fi
+	# Extract the DOI and strip the "doi:" prefix if it exists
+	doi=$(pdfinfo "$1" | grep -ioP "10\.\d{4,9}/[-._;()/:A-Z0-9]+" ||
+		pdftotext "$1" - | grep -ioP "10\.\d{4,9}/[-._;()/:A-Z0-9]+" -m 1)
+	
+	[ -z "$doi" ] && echo "Error: Could not find DOI in PDF." && exit 1
 else
-    # If passed manually, strip "doi:" prefix just in case
-    doi="${1#doi:}"
+	# If passed manually, strip "doi:" prefix just in case
+	doi="${1#doi:}"
 fi
 
 # Check crossref.org for bibtex citation
 output=$(curl -X GET \
 	"https://api.crossref.org/works/$doi/transform/application/x-bibtex" \
-	-H 'User-Agent: dbarcene (mailto:david.barcene@utp.ac.pa)' \
+	-H "User-Agent: dbarcene (mailto:david.barcene@utp.ac.pa)" \
 	-w "\\n")
 
 formatted="${output#?}"
